
export const GET_ALL_SONGS_REQUEST = "GET_ALL_SONGS_REQUEST"
export const GET_ALL_SONGS_SUCCESS = "GET_ALL_SONGS_SUCCESS"
export const GET_ALL_SONGS_FAILURE = "GET_ALL_SONGS_FAILURE"
export const SET_SONG_PLAYLIST = "SET_SONG_PLAYLIST"