export const GET_USER_DETAILS_REQUEST = "GET_USER_DETAILS_REQUEST"
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS"
export const GET_USER_DETAILS_FAILURE = "GET_USER_DETAILS_FAILURE"